name: grey_silence
description: Bring back the sound and colour to this endless runner world!

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flame: ^0.22.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Retro
      fonts:
        - asset: assets/fonts/retro.ttf
